---
- hosts: webservers
  remote_user: ubuntu
  become: true
  vars_files:
    - group_vars/secrets.yml
    - group_vars/webservers.yml
  roles:
    - role: geerlingguy.nginx
      tags: init
    - role: geerlingguy.postgresql
      become: true
      tags: init,postgresql
    - role: galaxy_media_site
      tags: gms
