tasks:
  - name: Setup and start development server
    env:
      DJANGO_SETTINGS_MODULE: webapp.settings.dev
    init: |
      pip install -r requirements.txt
      cp .env.sample .env
    command: |
      cd webapp
      python manage.py migrate
      python manage.py runserver
