# Generated by Django 3.2 on 2021-11-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20211109_0606'),
        ('news', '0002_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.CharField(help_text='Enter valid markdown', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='external',
            field=models.URLField(help_text='Link to external content', null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='supporters',
            field=models.ManyToManyField(help_text='Show logos/links', to='events.Supporter'),
        ),
    ]
