# Generated by Django 3.2 on 2021-11-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20211109_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.CharField(help_text='Enter valid markdown', max_length=50000, null=True),
        ),
    ]
