# Generated by Django 3.2 on 2021-11-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.CharField(blank=True, help_text='Enter valid markdown', max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='external',
            field=models.URLField(blank=True, help_text='Link to external content', null=True),
        ),
    ]
