# Generated by Django 3.2 on 2021-11-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20211117_2214'),
        ('news', '0005_auto_20211117_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='supporters',
            field=models.ManyToManyField(blank=True, help_text='Show logos/links', null=True, to='events.Supporter'),
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='events.Tag'),
        ),
    ]
