# Generated by Django 3.2 on 2021-11-17 23:57

from django.db import migrations, models
import django.db.models.deletion
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20211117_2214'),
        ('news', '0006_auto_20211117_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='supporters',
            field=models.ManyToManyField(blank=True, help_text='Show logos/links', to='events.Supporter'),
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, to='events.Tag'),
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=news.models.get_upload_dir)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.news')),
            ],
        ),
    ]
