# Generated by Django 4.0.3 on 2022-08-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_news_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_tool_update',
            field=models.BooleanField(default=False),
        ),
    ]
