# Generated by Django 3.2 on 2021-11-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20211109_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='title',
            new_name='position',
        ),
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
