# Generated by Django 3.2 on 2021-11-11 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20211109_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
