# Generated by Django 3.2 on 2021-11-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_person_datetime_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='github',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
