# Generated by Django 4.0.3 on 2022-03-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_person_github'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='phone',
        ),
        migrations.AddField(
            model_name='person',
            name='ranking',
            field=models.IntegerField(blank=True, default=99),
        ),
    ]
