# Generated by Django 4.0.3 on 2023-02-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_alter_person_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='alumni',
            field=models.BooleanField(default=False),
        ),
    ]
