# Generated by Django 4.0.3 on 2025-10-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_person_alumni'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='founder',
            field=models.BooleanField(default=False),
        ),
    ]
