# Generated by Django 3.2 on 2021-11-09 02:40

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20211109_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(choices_display='WITH_GMT_OFFSET', default='Australia/Sydney'),
        ),
    ]
