# Generated by Django 3.2 on 2021-11-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20211109_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='body',
            field=models.CharField(blank=True, help_text='Enter valid markdown', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='external',
            field=models.URLField(blank=True, help_text='Link to external content', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='supporters',
            field=models.ManyToManyField(help_text='Show logos/links', to='events.Supporter'),
        ),
        migrations.AlterField(
            model_name='supporter',
            name='logo',
            field=models.FileField(upload_to='logos'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='material_icon',
            field=models.CharField(blank=True, help_text='A valid material design icon identifier. See: https://fonts.google.com/icons', max_length=50, null=True),
        ),
    ]
