# Generated by Django 3.2 on 2021-11-11 00:57

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20211109_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='supporters',
            field=models.ManyToManyField(help_text='Display logos and links for a supporter.', to='events.Supporter'),
        ),
        migrations.AlterField(
            model_name='event',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(blank=True, choices_display='WITH_GMT_OFFSET', default='Australia/Sydney', null=True),
        ),
    ]
