# Generated by Django 3.2 on 2021-11-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.JSONField(blank=True, help_text='Valid JSON string', null=True),
        ),
    ]
