# Generated by Django 3.2 on 2021-11-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='supporters',
            field=models.ManyToManyField(blank=True, help_text='Display logos and links for a supporter.', to='events.Supporter'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, to='events.Tag'),
        ),
    ]
