# Generated by Django 3.2 on 2021-11-17 22:14

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_eventimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='body',
            field=models.CharField(blank=True, help_text='Enter valid markdown.\n            Add event images at the bottom of the page, and tag them\n            in markdown like so:\n            <pre> ![alt text](img1) <br> ![alt text](img2) </pre>', max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.FileField(upload_to=events.models.get_upload_dir),
        ),
    ]
