# Generated by Django 3.2 on 2021-11-22 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='published',
            new_name='is_published',
        ),
    ]
