# Generated by Django 3.2 on 2021-11-22 06:46

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_rename_published_event_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.JSONField(blank=True, default=events.models.default_address, help_text='Valid JSON string', null=True),
        ),
    ]
