# Generated by Django 3.2 on 2021-12-01 04:56

from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_event_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.JSONField(blank=True, default=events.models.default_address, help_text='Valid JSON string. Will be rendered as a table.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='body',
            field=models.CharField(blank=True, help_text='Enter valid GitHub markdown.\n    We\'re using <b>"code-friendly" mode</b>, so __ and _ will be rendered literally!\n    Use * and ** instead.\n    \n    <br>\n    Upload event images at the bottom of the page, and tag them\n    in markdown like so:\n    <pre>\n     <span style="color: #79AEC8"># the URI will replace img&lt;N&gt; after save </span>\n     ![alt text](img1)\n\n     <span style="color: #79AEC8"># Use an image tag to define size. Defaults to 100% max-width.</span>\n     &lt;img src="img2" width=200&gt; </pre>\n     ', max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Shown in list (icon) and post views.', to='events.Tag'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.eventlocation'),
        ),
    ]
