# Generated by Django 3.2 on 2021-12-01 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20211201_0456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='address',
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(help_text='This will be rendered as a table.', null=True, on_delete=django.db.models.deletion.CASCADE, to='events.eventlocation'),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='name',
            field=models.CharField(blank=True, help_text='All fields are optional. Only populated fields will be displayed.', max_length=100, null=True),
        ),
    ]
