# Generated by Django 3.2 on 2021-12-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20211201_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlocation',
            name='postal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
