# Generated by Django 3.2 on 2021-12-01 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_eventlocation_postal'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlocation',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
