# Generated by Django 3.2 on 2021-12-02 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_eventlocation_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, help_text='This will be rendered as a table.', null=True, on_delete=django.db.models.deletion.CASCADE, to='events.eventlocation'),
        ),
    ]
