# Generated by Django 3.2 on 2022-03-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_alter_event_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='material_icon',
            field=models.CharField(blank=True, help_text='A valid Material Design icon identifier to be displayed with the title. See: https://fonts.google.com/icons', max_length=50, null=True),
        ),
    ]
