# Generated by Django 3.2 on 2021-11-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='body',
            field=models.CharField(help_text='Enter valid markdown', max_length=2000),
        ),
        migrations.AlterField(
            model_name='notice',
            name='material_icon',
            field=models.CharField(blank=True, help_text='A valid material design icon identifier. See: https://fonts.google.com/icons', max_length=50, null=True),
        ),
    ]
