# Generated by Django 3.2 on 2021-11-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211109_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notice',
            name='material_icon',
            field=models.CharField(blank=True, help_text='A valid material design icon identifier. <a href="https://fonts.google.com/icons" target="_blank"> Browse icons here </a>', max_length=50, null=True),
        ),
    ]
