# Generated by Django 3.2 on 2021-11-21 22:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211121_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notice',
            name='enabled',
            field=models.BooleanField(default=False, help_text='Display on the Galaxy Australia landing page.'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='material_icon',
            field=models.CharField(blank=True, help_text='Optional. A valid Material Design icon identifier. <a href="https://fonts.google.com/icons" target="_blank"> Browse icons here </a>', max_length=50, null=True),
        ),
    ]
