# Generated by Django 3.2 on 2021-11-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211121_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='enabled',
            field=models.BooleanField(default=False, help_text='Display on the Galaxy Australia landing page.', null=True),
        ),
    ]
