# Generated by Django 3.2 on 2021-11-21 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_notice_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='datetime_created',
        ),
        migrations.AddField(
            model_name='notice',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
