# Generated by Django 3.2 on 2022-01-18 06:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_notice_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='order',
            field=models.IntegerField(blank=True, help_text='Order of display on the landing page when multiple Notices are enabled (i.e. lowest value shown first)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='notice',
            name='body',
            field=models.CharField(help_text='Enter valid GitHub markdown -\n    <a href="https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax" target="_blank">see markdown guide</a>.\n    We\'re using <b>"code-friendly" mode</b>, so __ and _ will be rendered\n    literally! Use * and ** for italics/bold instead.\n    ', max_length=2000),
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice_class',
            field=models.CharField(choices=[('success', 'info'), ('warning', 'warning'), ('danger', 'danger')], default='success', max_length=16),
        ),
    ]
