# Generated by Django 3.2 on 2022-02-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220118_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Unpublished content is visible to admin users only. Use this to review content before release to public users.'),
        ),
    ]
