# Generated by Django 3.2 on 2022-02-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_notice_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_class',
            field=models.CharField(choices=[('', 'info'), ('success', 'warning'), ('warning', 'danger'), ('danger', 'none')], default='', max_length=16),
        ),
    ]
