# Generated by Django 3.2 on 2022-02-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_notice_notice_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='display_title',
            field=models.BooleanField(default=True, help_text="Don't show the title when displaying the notice"),
        ),
    ]
