# Generated by Django 3.2 on 2022-03-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_notice_display_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='material_icon',
            field=models.CharField(blank=True, help_text='Optional. A valid Material Design icon identifier to be displayed with the title. <a href="https://fonts.google.com/icons" target="_blank"> Browse icons here </a>', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice_class',
            field=models.CharField(choices=[('info', 'info'), ('warning', 'warning'), ('danger', 'danger'), ('none', 'none')], default='', help_text="A style class to set a color schema for the notice. Select 'none' for no styling (e.g. inserting an image).", max_length=16),
        ),
    ]
