# Generated by Django 4.0.3 on 2022-03-29 00:29

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20220301_0533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=news.models.get_upload_dir)),
            ],
        ),
    ]
