# Generated by Django 4.0.3 on 2022-03-29 00:34

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=home.models.get_upload_path)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
