# Generated by Django 4.0.3 on 2022-11-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    def create_main_site(self, schema_editor):
        """Create the default 'main' site."""
        Subsite = self.get_model("home", "Subsite")
        main_site = Subsite.objects.create(name='main')
        Notice = self.get_model("home", "Notice")
        for n in Notice.objects.all():
            n.subsites.add(main_site)

    def reverse_create_main_site(self, schema_editor):
        """Revoke the default 'main' site.

        This is a no-op since Subsite will be removed anyway.
        """
        pass

    dependencies = [
        ('home', '0018_mediaimage_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='notice',
            name='subsites',
            field=models.ManyToManyField(help_text='Select which subdomain sites should display the notice.', to='home.subsite'),
        ),
        migrations.RunPython(create_main_site, reverse_create_main_site),
    ]
