# Generated by Django 4.0.3 on 2022-11-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_subsite_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='short_description',
            field=models.CharField(default='SHORT DESCRIPTION PLACEHOLDER - PLEASE UPDATE', help_text='This will be displayed on the landing page.', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notice',
            name='body',
            field=models.CharField(help_text='<b>This text will be displayed on a dedicated webpage.</b><br><br>Enter valid GitHub markdown -\n    <a href="https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax" target="_blank">see markdown guide</a>.\n    We\'re using <b>"code-friendly" mode</b>, so __ and _ will be rendered\n    literally! Use * and ** for italics/bold instead.\n    ', max_length=10000),
        ),
    ]
