# Generated by Django 4.0.3 on 2022-11-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_notice_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='body',
            field=models.CharField(help_text='<b>This text will be displayed on a dedicated webpage</b> - if this field is blank, no link will be displayed.<br><br>Enter valid GitHub markdown -\n    <a href="https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax" target="_blank">see markdown guide</a>.\n    We\'re using <b>"code-friendly" mode</b>, so __ and _ will be rendered\n    literally! Use * and ** for italics/bold instead.\n    ', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice_class',
            field=models.CharField(choices=[('info', 'info'), ('warning', 'warning'), ('danger', 'danger'), ('none', 'none')], default='', help_text="A style class to set a color schema for the notice. Select 'none' for no styling (e.g. inserting an image). Notices with the 'danger' class will always be displayed. All other notices will be cycled through when multiple are displayed.", max_length=16),
        ),
    ]
