# Generated by Django 4.0.3 on 2022-11-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_notice_body_alter_notice_notice_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='body',
            field=models.CharField(blank=True, help_text='<b>This text will be displayed on a dedicated webpage</b> - if this field is blank, no link will be displayed.<br><br>Enter valid GitHub markdown -\n    <a href="https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax" target="_blank">see markdown guide</a>.\n    We\'re using <b>"code-friendly" mode</b>, so __ and _ will be rendered\n    literally! Use * and ** for italics/bold instead.\n    ', max_length=10000, null=True),
        ),
    ]
