# Generated by Django 4.0.3 on 2022-12-08 03:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_notice_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='static_display',
            field=models.BooleanField(default=False, help_text="Display the notice as a static block beneath the GA logo. Should only ever be checked for <b style='color: firebrick;'>a single, high-priority notice</b> to prevent cluttering of the landing page. Static notices display the body instead of  the short description and do not link to a webpage."),
        ),
        migrations.AlterField(
            model_name='notice',
            name='body',
            field=models.CharField(blank=True, help_text='<b>This text will be displayed on a dedicated webpage</b> that is linked from the landing page notice. - if this field is blank, there will be no link.<br><br>Enter valid GitHub markdown -\n    <a href="https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax" target="_blank">see markdown guide</a>.\n    We\'re using <b>"code-friendly" mode</b>, so __ and _ will be rendered\n    literally! Use * and ** for italics/bold instead.\n    ', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='material_icon',
            field=models.CharField(blank=True, help_text='Optional. A valid Material Design icon ID to be displayed with the title (e.g. <em>check_box</em>). <a href="https://fonts.google.com/icons" target="_blank"> Browse icons here </a>', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice_class',
            field=models.CharField(choices=[('info', 'info'), ('warning', 'warning'), ('danger', 'danger'), ('none', 'image')], default='', help_text='A style class to set a color scheme for the notice. Select <em>image</em> for styling an image (the body should be an <code>&lt;img&gt;</code> tag only). The other classes are standard bootstrap styling (info: blue, warning: orange, danger: red).', max_length=16),
        ),
        migrations.AlterField(
            model_name='notice',
            name='order',
            field=models.IntegerField(blank=True, help_text='Display order on the landing page when multiple <em>static</em> notices are enabled (i.e. lowest value shown first)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='notice',
            name='short_description',
            field=models.CharField(help_text='This will be displayed on the landing page (200 char max) as plain text or inline HTML e.g. &lt;a&gt;, &lt;b&gt;. If <em>rotating</em> display (default), this will be shown as a single line of text above the navbar, which will be cut off if too long, especially on small screens!', max_length=200),
        ),
    ]
