# Generated by Django 4.0.3 on 2022-12-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_notice_static_display_alter_notice_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='body',
            field=models.CharField(blank=True, help_text='Enter valid GitHub markdown -\n    <a href="https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax" target="_blank">see markdown guide</a>.\n    We\'re using <b>"code-friendly" mode</b>, so __ and _ will be rendered\n    literally! Use * and ** for italics/bold instead.\n    <br><br>Unless <em>static display</em> is enabled, <b>This text will be displayed on a dedicated webpage</b> that is linked to from the landing page notice. If this field is left blank, there will be no link.', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='display_title',
            field=models.BooleanField(default=True, help_text='Show the notice title when displaying as a static notice. The title is always shown on the notice webpage for non-static (rotating) notices.'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='material_icon',
            field=models.CharField(blank=True, help_text='Optional. A valid Material Design icon ID to be displayed with the title (e.g. <em>check_box</em>). <a href="https://fonts.google.com/icons" target="_blank"> Browse 2500+ icons here </a>.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice_class',
            field=models.CharField(choices=[('info', 'info'), ('warning', 'warning'), ('danger', 'danger'), ('none', 'image')], default='', help_text="\n<ul style='margin-left: 2rem;'>\n    <li style='list-style: disc;'>\n        A style class to set a color scheme for the notice - uses\n        <a\n            href='https://getbootstrap.com/docs/5.0/components/alerts/'\n            target='_blank'\n        >standard bootstrap styling</a>\n        (\n            <em>info</em>: blue,\n            <em>warning</em>: orange,\n            <em>danger</em>: red\n        ).\n    </li>\n    <li style='list-style: disc;'>\n        Use the <em>image</em> class for displaying an image. For this,\n        the body should consist of an HTML <code>&lt;img&gt;</code> tag\n        only (or markdown equivalent).\n    </li>\n    <li style='list-style: disc;'>\n        Static notices show the <b>body</b> on the landing page instead\n        of the <b>short description</b> and do not link to a webpage.\n    </li>\n    <li style='list-style: disc;'>\n        An image notice will always be displayed as a static block, with\n        no title/description text. Use for displaying banners e.g.\n        event posters.\n    </li>\n</ul>\n", max_length=16),
        ),
        migrations.AlterField(
            model_name='notice',
            name='short_description',
            field=models.CharField(help_text="\n<ul style='margin-left: 2rem;'>\n    <li style='list-style: disc;'>\n        This will be displayed on the landing page (200 char max) as plain\n        text or inline HTML (e.g.\n        <code>&lt;a&gt;</code>,\n        <code>&lt;b&gt;</code>\n        tags).\n    </li>\n    <li style='list-style: disc;'>\n        If not <em>static</em> display (default), this will be shown as a\n        single line of text above the navbar,\n        <b>which will be cut off if too long</b>,\n        especially on small screens!\n    </li>\n    <li style='list-style: disc;'>\n        If <em>static</em> display is enabled, this field is ignored in favour\n        of the <em>title</em> and <em>body</em> fields.\n    </li>\n</ul>\n", max_length=200),
        ),
        migrations.AlterField(
            model_name='notice',
            name='static_display',
            field=models.BooleanField(default=False, help_text="\n<ul style='margin-left: 2rem;'>\n    <li style='list-style: disc;'>\n        Display the notice as a static block beneath the GA logo, rather than\n        the default rotating notice (i.e. the banner beneath the navbar).\n    </li>\n    <li style='list-style: disc;'>\n        Ideally, this should only be checked for\n        <b style='color: firebrick;'>a single, high-priority notice</b>\n        to prevent cluttering of the landing page.\n    </li>\n    <li style='list-style: disc;'>\n        Static notices show the <b>body</b> on the landing page instead\n        of the <b>short description</b> and do not link to a webpage.\n    </li>\n    <li style='list-style: disc;'>\n        Notices with <em>image</em> class always have static display,\n        so this option will be ignored.\n    </li>\n</ul>\n"),
        ),
    ]
