# Generated by Django 4.0.3 on 2022-12-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_notice_body_alter_notice_display_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='short_description',
            field=models.CharField(blank=True, help_text="\n<ul style='margin-left: 2rem;'>\n    <li style='list-style: disc;'>\n        This will be displayed on the landing page (200 char max) as plain\n        text or inline HTML (e.g.\n        <code>&lt;a&gt;</code>,\n        <code>&lt;b&gt;</code>\n        tags).\n    </li>\n    <li style='list-style: disc;'>\n        If not <em>static</em> display (default), this will be shown as a\n        single line of text above the navbar,\n        <b>which will be cut off if too long</b>,\n        especially on small screens!\n    </li>\n    <li style='list-style: disc;'>\n        If <em>static</em> display is enabled, this field is ignored in favour\n        of the <em>title</em> and <em>body</em> fields.\n    </li>\n</ul>\n", max_length=200, null=True),
        ),
    ]
