# Generated by Django 4.0.3 on 2022-12-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_notice_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='body',
            field=models.CharField(blank=True, help_text='\n<ul style=\'margin-left: 2rem;\'>\n    <li style=\'list-style: disc;\'>\n        Enter valid GitHub markdown -\n    <a href="https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax" target="_blank">see markdown guide</a>.\n    We\'re using <b>"code-friendly" mode</b>, so __ and _ will be rendered\n    literally! Use * and ** for italics/bold instead.\n    \n    </li>\n    <li style=\'list-style: disc;\'>\n        Unless <em>static display</em> is enabled,\n        <b>This text will be displayed on a dedicated webpage</b>\n        that is linked to from the landing page notice.\n        If this field is left blank, there will be no link.\n    </li>\n    <li style=\'list-style: disc;\'>\n        When using the <em>image</em> notice class, images will be rendered\n        with full width and max-height of 250px. You can override this by using\n        an <code>&lt;img&gt;</code> tag and setting the <code>style</code>\n        attribute.\n    </li>\n</ul>\n', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice_class',
            field=models.CharField(choices=[('info', 'info'), ('warning', 'warning'), ('danger', 'danger'), ('none', 'image')], default='', help_text="\n<ul style='margin-left: 2rem;'>\n    <li style='list-style: disc;'>\n        A style class to set a color scheme for the notice - uses\n        <a\n            href='https://getbootstrap.com/docs/5.0/components/alerts/'\n            target='_blank'\n        >standard bootstrap styling</a>\n        (\n            <em>info</em>: blue,\n            <em>warning</em>: orange,\n            <em>danger</em>: red\n        ).\n    </li>\n    <li style='list-style: disc;'>\n        Use the <em>image</em> class for displaying an image. For this,\n        the body should consist of an HTML <code>&lt;img&gt;</code> tag\n        only (or markdown equivalent).\n    </li>\n    <li style='list-style: disc;'>\n        Static notices show the <b>body</b> on the landing page instead\n        of the <b>short description</b> and do not link to a webpage.\n    </li>\n    <li style='list-style: disc;'>\n        An image notice will always be displayed as a static block, with\n        no title/description text. Use for displaying banners e.g.\n        event posters.\n    </li>\n    <li>\n        Note that wide images work much better than square ones!\n    </li>\n</ul>\n", max_length=16),
        ),
    ]
