# Generated by Django 4.0.3 on 2022-12-12 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_notice_body_alter_notice_notice_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='body',
            field=models.CharField(blank=True, help_text='\n    <ul style=\'margin-left: 2rem;\'>\n        <li style=\'list-style: disc;\'>\n            Enter valid GitHub markdown -\n    <a href="https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax" target="_blank">see markdown guide</a>.\n    We\'re using <b>"code-friendly" mode</b>, so __ and _ will be rendered\n    literally! Use * and ** for italics/bold instead.\n    \n        </li>\n        <li style=\'list-style: disc;\'>\n            Unless <em>static display</em> is enabled,\n            <b>This text will be displayed on a dedicated webpage</b>\n            that is linked to from the landing page notice.\n            If this field is left blank, there will be no link.\n        </li>\n        <li style=\'list-style: disc;\'>\n            When using the <em>image</em> notice class, images will be rendered\n            with full width and max-height of 250px. You can override this by using\n            an <code>&lt;img&gt;</code> tag and setting the <code>style</code>\n            attribute.\n        </li>\n    </ul>\n    ', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='display_title',
            field=models.BooleanField(default=True, help_text='Show the notice title when displaying as a static notice. This option is ignored for image notices.'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='material_icon',
            field=models.CharField(blank=True, help_text='\n    Optional. A valid Material Design icon ID to be displayed with the title\n    (e.g. <em>check_box</em>).\n    <a href="https://fonts.google.com/icons" target="_blank">\n    Browse 2500+ icons here\n    </a>.\n    ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice_class',
            field=models.CharField(choices=[('info', 'info'), ('warning', 'warning'), ('danger', 'danger'), ('none', 'image')], default='', help_text="\n    <ul style='margin-left: 2rem;'>\n        <li style='list-style: disc;'>\n            A style class to set a color scheme for the notice - uses\n            <a\n                href='https://getbootstrap.com/docs/5.0/components/alerts/'\n                target='_blank'\n            >standard bootstrap styling</a>\n            (\n                <em>info</em>: blue,\n                <em>warning</em>: orange,\n                <em>danger</em>: red\n            ).\n        </li>\n        <li style='list-style: disc;'>\n            Use the <em>image</em> class for displaying an image. For this,\n            the body should consist of an HTML <code>&lt;img&gt;</code> tag\n            only (or markdown equivalent).\n        </li>\n        <li style='list-style: disc;'>\n            Image notices always have <em>static display</em>, with no\n            title/description text. Use for displaying banners e.g. event posters.\n        </li>\n        <li>\n            N.B. short/wide images work much better than square ones!\n        </li>\n    </ul>\n    ", max_length=16),
        ),
        migrations.AlterField(
            model_name='notice',
            name='short_description',
            field=models.CharField(blank=True, help_text="\n    <ul style='margin-left: 2rem;'>\n        <li style='list-style: disc;'>\n            This will be displayed on the landing page (200 char max) as plain\n            text or inline HTML (e.g.\n            <code>&lt;a&gt;</code>,\n            <code>&lt;b&gt;</code>\n            tags).\n        </li>\n        <li style='list-style: disc;'>\n            If not <em>static</em> display (default), this will be shown as a\n            single line of text above the navbar,\n            <b>which will be cut off if too long</b>,\n            especially on small screens!\n        </li>\n        <li style='list-style: disc;'>\n            If <em>static</em> display is enabled, this field is ignored in favour\n            of the <em>title</em> and <em>body</em> fields.\n        </li>\n    </ul>\n    ", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='static_display',
            field=models.BooleanField(default=False, help_text="\n    <ul style='margin-left: 2rem;'>\n        <li style='list-style: disc;'>\n            Display the notice as a static block beneath the GA logo, rather than\n            the default rotating notice (i.e. the banner beneath the navbar).\n        </li>\n        <li style='list-style: disc;'>\n            Ideally, this should be checked\n            <b style='color: firebrick;'>only for a single, high-priority notice</b>\n            to prevent cluttering of the landing page.\n        </li>\n        <li style='list-style: disc;'>\n            Static notices show the <b>body</b> on the landing page instead\n            of the <b>short description</b> and do not link to a webpage.\n        </li>\n        <li style='list-style: disc;'>\n            Notices with <em>image</em> class always have static display,\n            so this option will be ignored.\n        </li>\n    </ul>\n    "),
        ),
    ]
