# Generated by Django 4.0.3 on 2023-01-18 00:15

from django.db import migrations, models


def truncate_notice_descriptions(apps, schema_editor):
    Notice = apps.get_model('home', 'Notice')
    for notice in Notice.objects.filter(short_description__isnull=False):
        if len(notice.short_description) > 150:
            notice.short_description = notice.short_description[:147] + '...'
            notice.save()


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_notice_body_alter_notice_display_title_and_more'),
    ]

    operations = [
        migrations.RunPython(truncate_notice_descriptions),
        migrations.AlterField(
            model_name='notice',
            name='body',
            field=models.CharField(blank=True, help_text='\n    <ul style=\'margin-left: 2rem;\'>\n        <li style=\'list-style: disc;\'>\n            Enter valid GitHub markdown -\n    <a href="https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax" target="_blank">see markdown guide</a>.\n    We\'re using <b>"code-friendly" mode</b>, so __ and _ will be rendered\n    literally! Use * and ** for italics/bold instead.\n    \n        </li>\n        <li style=\'list-style: disc;\'>\n            <b>This text will be displayed on a dedicated webpage</b>\n            that is linked to from the landing page notice.\n            If this field is left blank, there will be no link.\n            For notices with <b>static display</b>, this will be displayed on\n            the landing page in a block element, in addition to the dedicated\n            webpage.\n        </li>\n        <li style=\'list-style: disc;\'>\n            When using the <em>image</em> notice class, images will be rendered\n            with full width and max-height of 250px. You can override this by\n            using an <code>&lt;img&gt;</code> tag and setting the\n            <code>style</code> attribute.\n        </li>\n        <li style=\'list-style: disc;\'>\n            When using the <em>image</em> notice class, you can upload an image\n            and link to it using the\n            <a href="/admin/home/mediaimage/">Media images</a> model.\n            Otherwise you might just link to images hosted elsewhere e.g.\n            github.\n        </li>\n    </ul>\n    ', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice_class',
            field=models.CharField(choices=[('info', 'info'), ('warning', 'warning'), ('none', 'image')], default='', help_text="\n    <ul style='margin-left: 2rem;'>\n        <li style='list-style: disc;'>\n            A style class to set a color scheme for the notice - uses\n            <a\n                href='https://getbootstrap.com/docs/5.0/components/alerts/'\n                target='_blank'\n            >standard bootstrap styling</a>\n            (\n                <em>info</em>: blue,\n                <em>warning</em>: orange,\n                <em>danger</em>: red\n            ).\n        </li>\n        <li style='list-style: disc;'>\n            Use the <em>image</em> class for displaying an image. For this,\n            the body should consist of an HTML <code>&lt;img&gt;</code> tag\n            only (or markdown equivalent).\n        </li>\n        <li style='list-style: disc;'>\n            Image notices always have <b>static display</b>, with no\n            title/description text. Use for displaying banners e.g. event posters.\n        </li>\n        <li style='list-style: disc;'>\n            Short/wide images work much better than square ones!\n        </li>\n    </ul>\n    ", max_length=16),
        ),
        migrations.AlterField(
            model_name='notice',
            name='short_description',
            field=models.CharField(blank=True, help_text="\n    <ul style='margin-left: 2rem;'>\n        <li style='list-style: disc;'>\n            This will be displayed on the landing page (200 char max) as plain\n            text or inline HTML (e.g.\n            <code>&lt;em&gt;</code>,\n            <code>&lt;b&gt;</code>\n            tags).\n        </li>\n        <li style='list-style: disc;'>\n            No <code>&lt;a&gt;</code> tags please, as this creates a confusing\n            user experience (link within link).\n        </li>\n        <li style='list-style: disc;'>\n            This will be shown as a single line of text above the navbar,\n            <b>which will be cut off if too long</b>,\n            especially on small screens! Please check the length is reasonable\n            before publishing.\n        </li>\n    </ul>\n    ", max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='static_display',
            field=models.BooleanField(default=False, help_text="\n    <ul style='margin-left: 2rem;'>\n        <li style='list-style: disc;'>\n            Display the notice as a static block beneath the GA logo, in addition\n            to the default rotating notice (i.e. the banner beneath the navbar).\n        </li>\n        <li style='list-style: disc;'>\n            Ideally, this should be checked\n            <b style='color: firebrick;'>only for a single, high-priority notice</b>\n            to prevent cluttering of the landing page.\n        </li>\n        <li style='list-style: disc;'>\n            Static notices show the <b>body</b> on the landing page in addition\n            to the <b>short description</b>. If the block notice is dismissed\n            by the user, they can still access and click through the rotating\n            notice.\n        </li>\n        <li style='list-style: disc;'>\n            Notices with <em>image</em> class always have static display,\n            so this option will be ignored.\n        </li>\n    </ul>\n    "),
        ),
    ]
