# Generated by Django 4.0.3 on 2023-01-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_notice_body_alter_notice_notice_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_class',
            field=models.CharField(choices=[('info', 'info'), ('warning', 'warning'), ('none', 'image')], default='', help_text="\n    <ul style='margin-left: 2rem;'>\n        <li style='list-style: disc;'>\n            A style class to set a color scheme for the notice - uses\n            <a\n                href='https://getbootstrap.com/docs/5.0/components/alerts/'\n                target='_blank'\n            >standard bootstrap styling</a>\n            (\n                <em>info</em>: blue,\n                <em>warning</em>: orange,\n            ).\n        </li>\n        <li style='list-style: disc;'>\n            Use the <em>image</em> class for displaying an image. For this,\n            the body should consist of an HTML <code>&lt;img&gt;</code> tag\n            only (or markdown equivalent).\n        </li>\n        <li style='list-style: disc;'>\n            Image notices always have <b>static display</b>, with no\n            title/description text. Use for displaying banners e.g. event posters.\n        </li>\n        <li style='list-style: disc;'>\n            Short/wide images work much better than square ones!\n        </li>\n    </ul>\n    ", max_length=16),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
