# Generated by Django 4.0.3 on 2023-02-10 00:43

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_notice_notice_class_alter_notice_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='subsites',
            field=models.ManyToManyField(default=home.models.default_subsite, help_text='Select which subdomain sites should display the notice.', to='home.subsite'),
        ),
    ]
