# Generated by Django 4.0.3 on 2024-01-24 04:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_coverimage_img_alter_coverimage_max_height_px'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverimage',
            name='max_height_px',
            field=models.IntegerField(default=300, help_text='\n    For most images this should be left at the default (300px).\n    For more square images this can be increased, but try not to let the image\n    taking over the whole landing page.\n    ', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Max height (px)'),
        ),
    ]
