# Generated by Django 4.0.3 on 2024-01-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_coverimage_max_height_px'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverimage',
            name='title',
            field=models.CharField(blank=True, help_text='This will be used to identify the image in the web admin, and for accessibility purposes (i.e. screen-readers) on the webpage.', max_length=100),
        ),
    ]
