# Generated by Django 4.0.3 on 2024-01-24 04:07

import django.core.validators
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_alter_coverimage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverimage',
            name='img',
            field=models.FileField(help_text='\n    An ideal resolution for banner-style images is 1000x300px. It is\n    recommended to publish the image only after viewing the landing page to\n    confirm that the display is acceptable.\n    ', upload_to=home.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='coverimage',
            name='max_height_px',
            field=models.IntegerField(default=300, help_text='\n    For most images this should be left at the default (300px).\n    For more square images this can be increased, but try not to let the image\n    taking over the whole landing page. If you want an image to span the full\n    width, try increasing this value.\n    ', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Max height (px)'),
        ),
    ]
