# Generated by Django 4.0.3 on 2024-01-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_alter_coverimage_img_alter_coverimage_max_height_px'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_class',
            field=models.CharField(choices=[('info', 'info'), ('warning', 'warning'), ('none', 'image')], default='', help_text='\n    <ul style=\'margin-left: 2rem;\'>\n        <li style=\'list-style: disc;\'>\n            A style class to set a color scheme for the notice - uses\n            <a\n                href=\'https://getbootstrap.com/docs/5.0/components/alerts/\'\n                target=\'_blank\'\n            >standard bootstrap styling</a>\n            (<em>info</em>: blue, <em>warning</em>: orange).\n        </li>\n        <li style=\'list-style: disc;\'>\n            Use the <em>Cover Image</em> model for displaying banner images.\n            <span class="text-danger">\n              The <em>image</em> class is deprecated\n            </span>\n            - existing image notices should be migrated to\n            <em>Cover Image</em> records.\n        </li>\n    </ul>\n    ', max_length=16),
        ),
    ]
