# Generated by Django 4.0.3 on 2024-01-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_coverimage_auto_full_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverimage',
            name='link_url',
            field=models.CharField(blank=True, help_text='If set, clicking the image will open this URL. For external URLs, the link will open in a new tab.', max_length=255, null=True),
        ),
    ]
