# Generated by Django 4.2.13 on 2024-07-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_coverimage_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverimage',
            name='auto_full_width',
            field=models.BooleanField(default=True, help_text="Automatically set the image width to 100% of the screen width. This option overrides 'Max height'. Use this option for banner-style images!"),
        ),
    ]
