name: Deploy to dev server

on:
  workflow_run:
    workflows: ["Django tests"]
    types:
      - completed
    branches:
      - dev
  workflow_dispatch: {}  # For local testing with act

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deployment
    concurrency:
      group: deploy-dev
      cancel-in-progress: true

    steps:
      - name: Clone Infrastructure Repository
        run: git clone https://github.com/usegalaxy-au/infrastructure.git infrastructure

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible packaging

      - name: Install ssh keys
        # For reference: https://stackoverflow.com/a/70447517
        run: |
          install -m 600 -D /dev/null ~/.ssh/galaxy
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/galaxy
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Add VAULT password
        run: |
          echo "${{ secrets.ANSIBLE_VAULT_PASS }}" > infrastructure/.vault_pass.txt

      - name: Install ansible roles
        run: |
          cd infrastructure
          ansible-galaxy install -p roles -r requirements.yml

      - name: Run Ansible Playbook
        run: |
          cd infrastructure
          ansible-playbook -i hosts --tags update --key-file ~/.ssh/galaxy galaxy-media_dev_playbook.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'
          ANSIBLE_REMOTE_USER: ${{ secrets.SSH_USER }}
