name: Django tests

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  DJANGO_SECRET_KEY: secret
  HOSTNAME: 127.0.0.1:5000
  DB_NAME: gms
  DB_USER: gms
  DB_PASSWORD: secret
  MAIL_FROM_ADDRESS: galaxy-no-reply@usegalaxy.org.au
  MAIL_TO_ADDRESS: help@genome.edu.au
  MAIL_USE_TLS: true
  MAIL_HOSTNAME: smtp.mailtrap.io
  MAIL_SMTP_PORT: 2525
  MAIL_SMTP_USERNAME: ""
  MAIL_SMTP_PASSWORD: ""
  RECAPTCHA_SITE_KEY: ""
  RECAPTCHA_SECRET_KEY: ""
  TOOL_UPDATE_EMAILS: test-notification@example.com
  GALAXY_URL: https://usegalaxy.org.au
  GALAXY_API_KEY: ""
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd webapp && python manage.py test
