name: Preview on Gitpod

on:
  pull_request_target:
    types: [opened]

jobs:
  gitpod-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Check out base branch
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Comment with Gitpod link
        env:
          GH_TOKEN: ${{ github.token }}
          REPO_URL: "https://github.com/${{ github.event.pull_request.head.repo.full_name }}/tree/${{ github.event.pull_request.head.ref }}"
        run: |
          GITPOD_URL="https://gitpod.io/#${REPO_URL}"
          printf "View the preview: [Gitpod]($GITPOD_URL)\n\nSee the [GMS on GitPod docs](../wiki/Development#contributing)" > gitpod_comment.md
          gh pr comment ${{ github.event.pull_request.number }} --body "$(cat gitpod_comment.md)"
